sap.security.services.xsuaa.clientid=sb-demo-xsuaa-auth-srv!t636379
sap.security.services.xsuaa.clientsecret=34a5436c-d206-4865-a044-1373f9318ab9$yJLsrC8PgdHCGvAU1rzFBUfMjt5edeldwTkvCRs98Go=
sap.security.services.xsuaa.url=https://c50ca044trial.authentication.us10.hana.ondemand.com
sap.security.services.xsuaa.identityzone=c50ca044trial
sap.security.services.xsuaa.identityzoneid=f714d272-fa0c-4457-a42a-57444430b9e7
sap.security.services.xsuaa.tenantid=f714d272-fa0c-4457-a42a-57444430b9e7
sap.security.services.xsuaa.tenantmode=dedicated
sap.security.services.xsuaa.sburl=https://internal-xsuaa.authentication.us10.hana.ondemand.com
sap.security.services.xsuaa.apiurl=https://api.authentication.us10.hana.ondemand.com
sap.security.services.xsuaa.verificationkey=-----BEGIN PUBLIC KEY-----\n\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu5k0ZskdPJFzUf+qOF8h\n\
AOJfJpI3QT05wuJ87RDI98GcoAAHbcgenInAMgdS2HF5a6oJ/0AzbjRdFmJBXlHw\n\
B2GmNLar+LzlCudvYd0v1a62NzpgppeiudcU9S8sIQMSd/ppuxst0leSmtgluI6N\n\
J2rbQX201tndO61BByT4ltrNYIHvY6qxNYQltJ1euIxVAWLpN4m/GZbkgPU6WV87\n\
zq04Lg712hDxkGVLWf/iteydTBJFsITMGN8mnkThG2F2pOz/PHN6AFXDoA31OFxd\n\
LoxmlKM15obmkcsov2HmTDRwnIsd57w1yYKi7NOsf8Oz2Ei23x/fFj8u9yngZxTc\n\
vQIDAQAB\n\
-----END PUBLIC KEY-----
sap.security.services.xsuaa.xsappname=demo-xsuaa-auth-srv!t636379
sap.security.services.xsuaa.subaccountid=f714d272-fa0c-4457-a42a-57444430b9e7
sap.security.services.xsuaa.uaadomain=authentication.us10.hana.ondemand.com
sap.security.services.xsuaa.zoneid=f714d272-fa0c-4457-a42a-57444430b9e7
sap.security.services.xsuaa.credential-type=binding-secret
sap.security.services.xsuaa.serviceInstanceId=fbf44dcf-0dfc-4900-8f3d-2d6073d4125b
